### PR TITLE
Updated tutorial information with pictures and some text

### PR DESCRIPTION
**Pull request by ThomasArts**
Unsure whether we want all images in 2015/img/ but that's where the individual pages seems to point to.

### CODE REVIEW

**Comment by agarwal** [comment]
Can you please add images to the cufp.org-media repo, and squash the commits of this PR (or just submit a new one). We do this to avoid bloating this repo with binaries. The URLs are fine; the images should go under `2015/img` as you've done.

**Comment by ThomasArts** [comment]
Ok. I copied the images to media and will make a pull request in a second. I am unsure how to fix my previous pull request, but will try to make a new one for cufp.org <http://cufp.org/> without pictures.
/thomas

---
Thomas Arts
CTO 
Quviq AB

thomas.arts@quviq.com
tel: +46 70 43 88567
http://www.quviq.com/

**Comment by ThomasArts** [comment]
Please pull or cherry-pick from commits. The pictures are now in different repo.

**Comment by agarwal** [comment]
Done as a single new commit a90487790527b0ae761bce35cf82ac3ca41f2622.

**Pull request closed without merging**
