### PR TITLE
Canceled Zach's tutorial

### PR DESCRIPTION
**Pull request by ThomasArts**
Author has withdrawn
I left the text, but made a note that it was canceled. If you think it is better to remove completely, please do so.

### CODE REVIEW

**Comment by agarwal** [comment]
I went ahead and removed completely, mostly because the scripts don't specifically support the concept of *cancelled*. I should probably add that.

**Comment by ThomasArts** [comment]
Hi Ashish

Some late minute changes... added a co-presenter for tutorial.
I added it as a patch, to make sure not to break anything in github.

Cheers
Thomas

**Comment by agarwal** [comment]
@ThomasArts Can you clarify. Is this about Zach's cancelled tutorial. Was the patch supposed to be attached to your email reply? I think that won't come through since you replied to a GitHub comment.

**Comment by agarwal** [comment]
Never mind. I got it in a separate email to a separate account! GitHub's notification system is quirky.

**Pull request merged**
