### PR TITLE
Add 2017 talk schedule

### PR DESCRIPTION
**Pull request by alang9**
I tried to view this locally, but got an error:

```
$ opam install cufporg --deps-only

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[WARNING] Rsync partially failed:
          symlink has no referent: "/home/alang/src/cufp.org/site/css/_foundation-icons.css"
          rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

[cufporg] /home/alang/src/cufp.org/ synchronized
The following dependencies couldn't be met:
  - cufporg -> core >= v0.9.1
Your request can't be satisfied:
  - No package matches core>=v0.9.1.

No solution found, exiting
```

### CODE REVIEW

**Comment by agarwal** [comment]
You might need to do an `opam update && opam upgrade`. Also, you might have stale build files, so try `make clean`.

**Comment by alang9** [comment]
I get a more helpful message now:

```
Your request can't be satisfied:
  - core>=v0.9.1 is not available because your system doesn't comply with ocaml-version >= "4.03.0".
```

**Comment by agarwal** [comment]
Right, I'm running ocaml 4.03.0. You can create a _switch_, i.e. `opam switch 4.03.0`. That'll take several minutes as you have to compile ocaml and all the libraries again.

**Comment by agarwal** [comment]
I made a few more commits and have published these changes.

**Pull request merged**
