### PR TITLE
Fix schedule for a talk

### PR DESCRIPTION
**Pull request by alang9**

### CODE REVIEW

**Comment by alang9** [comment]
Added a few more changes

**Comment by agarwal** [comment]
Thanks for adding the author affiliation. It is the _Commercial_ Users of FP, so I think knowing the affiliation of all speakers is important. Unfortunately, several are still missing.

**Comment by agarwal** [comment]
several --> most

**Comment by alang9** [comment]
Yea, unfortunately the question was not asked in the original CFP so I've sent out e-mails asking for speakers to submit their affiliation now.

**Pull request merged**
