### PR TITLE
Add tutorial entries for the CUFP site

### PR DESCRIPTION
**Pull request by roman**

### CODE REVIEW

**Comment by roman** [comment]
ping @agarwal

**Comment by agarwal** [comment]
Published. But note we really need an image for each speaker. I'll update the content to insert a dummy image for now, but please can you request an image from each speaker. Images go in the cufp.org-media repo, or provide them to me some other way and I'll add them.

**Comment by roman** [comment]
Hey @agarwal, do you know how do I do to add a prefix to the titles on the `index` template, I need to add a `T1 -`, `T2 -`, ..., etc to the titles of the tutorials, but not sure how to do it.

Thanks for any help you can provide.

Cheers.

**Comment by agarwal** [comment]
You can change the `title` field within the md file of each tutorial. For example, in `site/2016/2016-09-22_1330_1700_t3-kc-sivaramakrishnan-introduction-to-ocaml.md`, do this:

`- title: T3 - Introduction to OCaml`

Is that good enough or are not quite what you're looking for?

**Pull request merged**
