### PR TITLE
Update Ivan's bio

### PR DESCRIPTION
**Pull request by alang9**

### CODE REVIEW

**Comment by alang9** [comment]
Hi Ashish,

Would you mind publishing the changes?

Cheers,
Alex

**Comment by agarwal** [comment]
I published when I merged. Are you not seeing the change? I just visited http://cufp.org/2017/haskell-games-and-apps-for-ios-and-android.html and I am seeing the bio added in this commit.

**Comment by alang9** [comment]
Oh I see. For some reason my picture on the front page hasn't changed

**Comment by agarwal** [comment]
Must be a browser caching issue. Your new picture added in CUFP/cufp.org-media@1106b2c4ff3247b0a7f0e1aaa5b76c06a767798b shows for me.

**Comment by alang9** [comment]
I see. Thanks!

**Pull request merged**
