### PR TITLE
Updating for 2016

### PR DESCRIPTION
**Pull request by codemiller**

### CODE REVIEW

**Comment by agarwal** [comment]
Do you specifically need the URL `http://cufp.org/2016cfp/`, or would it be okay to make this instead `http://cufp.org/2016/cfp.html`?

Last year we had `2015cfp/` only because that URL had already got announced on mailing lists.

**Comment by codemiller** [comment]
It's nice to have the short form as well (it's just a redirect). We use this URL on Twitter and other places where brevity is advantageous.

**Comment by agarwal** [comment]
Did you want to go live with 2016? I can do that pretty fast whenever you say.. just need to find one picture for the front page.

**Comment by codemiller** [comment]
Yes, let's go live. Thanks!

**Comment by agarwal** [comment]
Done. We are live.

**Pull request merged**
