### PR TITLE
Call For Tutorials for CUFP-2016

### PR DESCRIPTION
**Pull request by roman**

### CODE REVIEW

**Comment by roman** [comment]
ping @agarwal

**Comment by agarwal** [comment]
Oops. I never got a notification for this. Just checked and there's nothing in my spam folder either, so not sure what happened. In future, please don't hesitate to ping me sooner.

Working on this now.

**Comment by agarwal** [comment]
The call for tutorials has been published. I also added a link from the front page.

**Comment by roman** [comment]
@agarwal Thank you very much... really happy this went out, cheers.

**Pull request merged**
